logger:
  level: "debug"
  encoding: "console"
  path: "stdout"

public_server:
  enable: true
  endpoint: "localhost"
  port: 8070

admin_server:
  enable: true
  endpoint: "localhost"
  port: 8071

application:
  app: "dialog-notifications"

storage:
  hosts:
    - "master-dialog"
  #    - "slave"
  port: 5432
  database: "dialog-local"
  username: "dialog-local-admin"
  password: "eephayl3eaph8Xo"
  ssl_mode: "disable"
  connection_attempts: 3

auth:
  enable: true
  conn:
    endpoint: social-network:7070